#!/bin/sh

set -e

python3 -m pip install -U 'elasticsearch>=8,<9'

systemctl daemon-reload

if systemctl is-active --quiet fs2es-indexer.service;
then
    systemctl restart fs2es-indexer.service
fi

if systemctl is-active --quiet rsyslog.service;
then
    systemctl restart rsyslog.service
fi