#!/bin/sh

set -e

# Create a virtual env for our dependencies
/usr/bin/python3 -m venv /opt/fs2es-indexer/

# Install our dependencies in this virtual env only
/opt/fs2es-indexer/bin/pip3 install 'elasticsearch>=8,<9'

/usr/bin/systemctl daemon-reload

if /usr/bin/systemctl is-active --quiet fs2es-indexer.service;
then
    /usr/bin/systemctl restart fs2es-indexer.service
fi

if /usr/bin/systemctl is-active --quiet rsyslog.service;
then
    /usr/bin/systemctl restart rsyslog.service
fi