#!/bin/sh

set -e

cd /opt/fs2es-indexer

# See https://www.debian.org/doc/packaging-manuals/python-policy/#distutils
python3 setup.py install --install-layout=deb

systemctl daemon-reload

if systemctl is-active --quiet fs2es-indexer.service;
then
    systemctl restart fs2es-indexer.service
fi